name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y ninja-build meson clang-tidy clang-format

      - name: Configure Meson debug build
        run: meson setup build_debug --buildtype=debug
      
      - name: Build debug
        run: meson compile -C build_debug

      - name: Configure Meson release build
        run: meson setup build --buildtype=release
      
      - name: Build release
        run: meson compile -C build

      - name: Run Clang-Tidy
        run: clang-tidy -p build {src/*.cpp,include/*.hpp} --use-color

      - name: Run Clang-Format Check
        run: clang-format --dry-run --Werror src/*.cpp include/*.hpp --verbose
